### ISSUE TITLE
参考書籍についての質問

### ISSUE THREAD

**Issue by mnhr4** [drsenri/Training_of_data_science#3]
『みんなのPython 第4版』か『Pythonによるデータ分析入門』を買おうと考えているんですが、
この2冊ならどちらがオススメか教えてください。
それとも、両方買った方が良いでしょうか。

**Comment by drsenri** [comment]
@mnhr4 
基本的に、以下の通りスコープが違います。
みんなのPython: そもそものPythonの説明
Pythonによるデータ分析入門: numpy, pandasの説明 (Pythonのことはある程度わかってる前提)

numpy, pandasについてはwebで検索すれば大抵の答えは手に入るため、より基本の部分である「みんなのPython」の方が本で持っておく価値があると思います (分析的な話はあまり出てこないです)。
あと最近読んだ本ですが、「仕事ではじめる機械学習」は機械学習はどういうものか・またどう使うかについて概要～簡単な理屈まで書かれており、かなり良い本です（こういうことが書かれている本少ないですが、実際に使う上ではこれこそが肝です）。
